# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/myDataScience',
                'doc_host': 'https://dirkkalmbach.github.io',
                'git_url': 'https://github.com/dirkkalmbach/myDataScience',
                'lib_path': 'myDataScience'},
  'syms': {'myDataScience.core': {'myDataScience.core.foo': ('core.html#foo', 'myDataScience/core.py')}}}