# AUTOGENERATED! DO NOT EDIT! File to edit: ../12_Analyse.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../12_Analyse.ipynb 3
def foo(): pass

# %% ../12_Analyse.ipynb 6
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
